FROM redash/redash:9.0.0-beta.b42121

ENV WORKERS_COUNT=${WORKERS_COUNT:-1}
ENV QUEUES=${QUEUES:-celery}

WORKDIR /app
RUN pip install --upgrade yfinance convertdate numpy pandas matplotlib

CMD /usr/local/bin/celery worker --app=redash.worker --beat -c$WORKERS_COUNT -Q$QUEUES -linfo --maxtasksperchild=10 -Ofair
