FROM redash/redash:preview

ENV WORKERS_COUNT=${WORKERS_COUNT:-1}
ENV QUEUES=${QUEUES:-celery}

WORKDIR /app
RUN pip install --upgrade yfinance fbprophet numpy pandas matplotlib

CMD /usr/local/bin/celery worker --app=redash.worker --beat -c$WORKERS_COUNT -Q$QUEUES -linfo --maxtasksperchild=10 -Ofair
